name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, muspelheim]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          VPN_SERVICE_PROVIDER: ${{ secrets.VPN_SERVICE_PROVIDER }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_TYPE: ${{ secrets.VPN_TYPE }}
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          WIREGUARD_PRESHARED_KEY: ${{ secrets.WIREGUARD_PRESHARED_KEY }}
          WIREGUARD_ADDRESSES: ${{ secrets.WIREGUARD_ADDRESSES }}
          FIREWALL_VPN_INPUT_PORTS: ${{ secrets.FIREWALL_VPN_INPUT_PORTS }}
          SLSKD_LISTEN_PORT: ${{ secrets.SLSKD_LISTEN_PORT }}
          GLUETUN_CONTROL_API_KEY: ${{ secrets.GLUETUN_CONTROL_API_KEY }}
          SLSKD_USERNAME: ${{ secrets.SLSKD_USERNAME }}
          SLSKD_PASSWORD: ${{ secrets.SLSKD_PASSWORD }}
          SLSKD_SLSK_USERNAME: ${{ secrets.SLSKD_SLSK_USERNAME }}
          SLSKD_SLSK_PASSWORD: ${{ secrets.SLSKD_SLSK_PASSWORD }}
        run: ./start.sh
